/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Web3HuntContentManager } from "./Web3HuntContentManager";

export { Web3HuntContentManager__factory } from "./factories/Web3HuntContentManager__factory";
