/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface Web3HuntContentManagerInterface extends utils.Interface {
  functions: {
    "stateChange(bytes[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "stateChange",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "stateChange",
    data: BytesLike
  ): Result;

  events: {
    "StateChange(address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StateChange"): EventFragment;
}

export type StateChangeEvent = TypedEvent<
  [string, string],
  { author: string; data: string }
>;

export type StateChangeEventFilter = TypedEventFilter<StateChangeEvent>;

export interface Web3HuntContentManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Web3HuntContentManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    stateChange(
      data_: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  stateChange(
    data_: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    stateChange(data_: BytesLike[], overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "StateChange(address,bytes)"(
      author?: null,
      data?: null
    ): StateChangeEventFilter;
    StateChange(author?: null, data?: null): StateChangeEventFilter;
  };

  estimateGas: {
    stateChange(
      data_: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    stateChange(
      data_: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
