
export type Project = {
  title: string;
  desc: string;
  image: string;
  votes: number,
  tags: Array<string>
}

export const PROJECTS = [
  {
    id: 1,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 2,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 3,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 4,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 5,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 6,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 7,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 8,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 9,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 10,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 11,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 12,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 13,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 14,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 15,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 16,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 17,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 18,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 19,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 20,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 21,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 22,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 23,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    id: 24,
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
];
