
export type Project = {
  title: string;
  desc: string;
  image: string;
  votes: number,
  tags: Array<string>
}

export const PROJECTS = [
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
  {
    title: 'Placeholder Title',
    desc: 'Collections or one-of-a-kind tokens with fully customizable properties',
    image: '/assets/images/placeholder_image.png',
    votes: 5,
    tags: ['Defi', 'Nft'],
  },
];
